### ISSUE TITLE
HTML entities in CSS content property

### ISSUE THREAD

**Issue by huygn** [huygn/til#80]
One usecase would be automatically adding space when a line text has no content - useful for form's error message placeholders.

```css
/* retains height when html content is empty */
.mdc-text-field-helper-text.mdc-text-field-helper-text--persistent:empty::after {
  display: inline;
  content: "\0000a0"; /* https://stackoverflow.com/a/190412/4328963 */
}
```
