### ISSUE TITLE
Darken styling

### ISSUE THREAD

**Issue by huygn** [huygn/til#83]
```css
.darken {
  box-shadow: inset 0px 0px 999px 100px rgba(0, 0, 0, .2);
},
```

even better:

```css
.hover-darken {
  transition: box-shadow .2s ease-out 0ms;
  &:hover {
    box-shadow: inset 0px 0px 999px 100px rgba(0, 0, 0, .2);
  }
}
```
