### ISSUE TITLE
Prevent iOS Safari from auto-zoom when touching an input

### ISSUE THREAD

**Issue by huygn** [huygn/til#90]
Why
> The browser will zoom if the font-size is less than 16px and the default font-size for form elements is 11px (at least in Chrome and Safari).

How
```css
@supports (-webkit-overflow-scrolling: touch) { 
  select,
  textarea,
  input {
    font-size: 16px;
  }
}
```

Ref:
https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone#comment89072459_16255670
