### ISSUE TITLE
Disable "over-scroll" effect on MacOS and iOS (touch devices)

### ISSUE THREAD

**Issue by huygn** [huygn/til#91]
ref: https://stackoverflow.com/questions/12046315/prevent-overscrolling-of-web-page
___

![main_large](https://user-images.githubusercontent.com/10569203/91252331-9aaf4380-e787-11ea-8a67-df02ace3a364.gif)

```css
body {
  overscroll-behavior-y: none;
}
```
